### ISSUE TITLE
Habitat Update Plan Version task?

### ISSUE THREAD

**Issue by nwright-nz** [chef-partners/azuredevops-habitat#2]
Hello,

Any chance of getting a 'Update plan version' task included in the Habitat Integrations (similar to the Chef VSTS integration task)? At present I'm using sed which is fine, but it would be great to see a task for this if at all possible.

Thanks very much!

**Comment by russellseymour** [comment]
Hello @nwright-nz,

In this case it does not make sense to update the `plan.sh` file like the Chef task, as it is not being published anywhere. There are a couple of ways that you can get version sync between Azure DevOps and Habitat.

# Use the BUILD_BUILDNUMBER environment variable

This can be done without updating the `plan.sh` file itself. The trick is to override the `pkg_version()` function in your `plan.sh` file. For example:

```bash
pkg_version() {

    # Set a default for the package version
    version="0.0.0"

    # Determine if the BUILD_BUILDNUMBER env var exists
    if [![ -z ${BUILD_BUILDNUMBER}]]
    then
        version=$BUILD_BUILDNUMBER
    fi

    echo $version
}
```

Now add the following function to the file, so that the version is updated:

```bash
do_before() {
    do_default_before
    update_pkg_version
}
```

Now when you plan runs, if it detects the environment variable `BUILD_BUILDNUMBER` (which is will when it runs on an Azure DevOps agent) the Habitat package will now have this as its build number.

# Use the task to expose the Habitat version to Azure Devops

We have just released version 2.x of the extension which includes a new task [Expose Habitat Build Variables](https://chef-partners.github.io/azuredevops-habitat/expose-build-variables.html).

By using this task and selecting the option to "Set Build Number" the Habitat version will now be used as the Azure DevOps build number.

Hope this helps.

**Comment by nwright-nz** [comment]
Hey @russellseymour - this is AWESOME. Thanks so much for all the info!
